name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: clang cl
      run: |
        fastlane --version
        gem update fastlane
        fastlane --version
