name: Test sdkmanager

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test MSYS2
      run: |
        ls "C:\ProgramData\Chocolatey\bin"
