name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: brew
      run: |
        brew --version
        brew tap aws/tap
        brew install aws-sam-cli
        
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: List installed packages
      run: pip list
    
    - name: Install pyyaml 5.2
      run: |
        pip uninstall -y pyyaml
        pip install "pyyaml==5.2"
    
    - name: Check pip version
      if: ${{ always() }}
      run: |
        pip --version
        pip list
        
    - name: Validate Newman
      run: |
       newman --version
        
