name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
      run: |
        du -h /opt/hostedtoolcache/Python/3.7.8
      
    - name: Validate Newman
      run: |
       newman --version
        
