name: Test sdkmanager

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install latest ndk
      run: echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk-bundle"

    - name: sdkmanager --list
      run: |
        sudo $ANDROID_HOME/tools/bin/sdkmanager --list
