name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: downgrade cmake
      run: |
        choco install cmake -y --version=3.8.1 --installargs 'ADD_CMAKE_TO_PATH=System'
    
    - name: clang cl
      run: |
        cmake --version
        cmake --help
        
    - name: check
      run: |
        Get-ChildItem -Path "C:\msys64\mingw64\bin"
        Write-Host "------"
        Get-ChildItem -Path "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/bin"
        
    - name: env
      run: env
        
