name: Test sdkmanager

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install ndk 20.0.5594570
      run: echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;20.0.5594570"

    - name: sdkmanager --list
      run: |
        sudo $ANDROID_HOME/tools/bin/sdkmanager --list
