name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: clang cl
      run: |
        $newPath = '/c/hello'
        $oldPath = [Environment]::GetEnvironmentVariable('path', 'machine');
        [Environment]::SetEnvironmentVariable('PATH', "$($newPath);$($oldPath)",'Machine');
        env
        
    - name: check
      run: |
        Get-ChildItem -Path "C:\msys64\mingw64\bin"
        Write-Host "------"
        Get-ChildItem -Path "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC"
        
    - name: env
      run: env
        
