name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run install
      run: bash ./aws-sam-cli.sh
    
    - name: Validate Newman
      run: |
       newman --version
        
