name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
      
    - name: Run install
      run: bash ./aws-sam-cli.sh
    
    - name: Validate Newman
      run: |
       newman --version
   
    - name: Pip list
      run: pip list
        
