name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Newman
      run: |
       sudo apt-get install newman
        
    - name: Validate Newman
      run: |
        newman --version
        
