name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: which dotnet
      run: |
        which dotnet
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --version
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: Install sdk and runtime
      run: |
        sudo apt-get install dotnet-sdk-2.1.202
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --version
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: ls
      run: ls ~/.dotnet/sdk
    
    - name: env
      run: env
