name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
    
    - name: Check pip version
      run: |
        pip --version
        pip --help
    
    - name: Check pyyaml
      run: |
        ls /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages
        echo "------"
        ls /opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages/pkg_resources
        
    - name: Validate Newman
      run: |
       newman --version
        
