name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: Install sdk and runtime
      run: bash ./dotnet-install.sh --version 2.1.202
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: path
      run: echo $path
