name: Test sdkmanager

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install cmake 3.10
      run: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.10.2.4988404"

    - name: sdkmanager --list
      run: |
        $ANDROID_HOME/tools/bin/sdkmanager --list
