name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '1.1.14', '2.1.202', '3.1.x' ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --version
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --version
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: ls
      run: ls /usr/share/dotnet/sdk
    
    - name: env
      run: env
