name: Test

on:
  push:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test Newman
      run: |
        newman --version
        
    - name: Test ghc
      run: |
        ghc --version
  
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.8'

    - name: Test ghc
      run: |
        ghc --version
        stack --version
        cabal --version
        
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test Newman
      run: |
        newman --version
        
    - name: Test ghc
      run: |
        ghc --version

