name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: ls
      run: ls /opt/hostedtoolcache/Python
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: List installed packages
      run: pip list
    
    - name: Install pyyaml 5.2
      run: |
        pip install "pyyaml==5.2"
    
    - name: Check pip version
      if: ${{ always() }}
      run: |
        ls /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages
        pip --version
        pip list
        
    - name: Validate Newman
      run: |
       newman --version
        
