name: Test

on:
  push:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test Newman
      run: |
        newman --version
        
    - name: Test ghc
      run: |
        ghc --version
  
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7.8
    
    - name: test Python
      run: |
        python --version
        pip list
        pip install --help
    
    - name: install Tensorflow
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install tensorflow
        
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test Newman
      run: |
        newman --version
        
    - name: Test ghc
      run: |
        ghc --version

