name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: Install sdk and runtime
      run: bash ./dotnet-install.sh --version 2.1.202 --verbose
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: ls
      run: ls /usr/share/dotnet/sdk
