name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test WinRM
      run: |
        winrm get winrm/config
        winrm.cmd set winrm/config/winrs @{MaxMemoryPerShellMB="1024"}
        Write-Host "-----"
        winrm get winrm/config
