name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: Install sdk and runtime
      run: bash ./dotnet-install.sh --version 3.0.100-rc1-014190
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes
