name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --version
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: Install sdk and runtime
      run: sudo bash ./dotnet-install.sh --version 2.1.202 --install-dir /usr/share/dotnet --verbose
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --version
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: ls
      run: ls ~/.dotnet/sdk
