name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
      run: |
        $newPath = "C:\msys64\mingw64\bin"
        echo "::add-path::/c/msys64/mingw64/bin"
        $env:path
        env
        
    - name: check
      run: |
        Get-ChildItem -Path "C:\msys64\mingw64\bin"
        Write-Host "-----------"
        Get-ChildItem -Path "C:\Program Files\Git\mingw64\bin"
        
