name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: which dotnet
      run: |
        which dotnet
        export DOTNET_CLI_TELEMETRY_OPTOUT=1
        ps aux
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --version
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: Install sdk and runtime
      run: |
        killall dotnet
        bash ./dotnet-install.sh --version 2.1.202 --install-dir /usr/share/dotnet --verbose
    
    - name: Show dotnet sdks and runtimes
      run: |
        dotnet --version
        dotnet --list-sdks
        dotnet --list-runtimes
        
    - name: ls
      run: ls /usr/share/dotnet/sdk
    
    - name: env
      run: env
