name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Check pyyaml
      run: |
        ls /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages
        
    - name: Validate Newman
      run: |
       newman --version
        
