name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
      
    - name: Run install
      run: bash ./aws-sam-cli.sh
    
    - name: Test aws sam cli
      env:
        SAM_CLI_TELEMETRY: 0
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        /opt/python-aws-sam-cli/3.7.7/x64/bin/sam --version
        /opt/python-aws-sam-cli/3.7.7/x64/bin/sam init --name sam-app --runtime nodejs10.x --dependency-manager npm --app-template hello-world
        cd sam-app
        /opt/python-aws-sam-cli/3.7.7/x64/bin/sam build
        /opt/python-aws-sam-cli/3.7.7/x64/bin/sam deploy --guided
    
    - name: Validate Newman
      run: |
       newman --version
   
    - name: Pip list
      run: pip list
        
