name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Check pyyaml
      run: |
        ls /opt/hostedtoolcache/Python
        
    - name: Validate Newman
      run: |
        Write-Host "Newman $(newman --version)"
        
