name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: clang cl
      run: |
        cmake --version
        clang --version
        
    - name: env
      run: env
        
