name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Add msys to path
      run: echo "##[add-path]C:\msys64\mingw64\bin"
    
    - name: Show path
      run: $env:path
        
    - name: check
      run: |
        clang --version
        Write-Host "-----------"
        Get-ChildItem -Path "C:\msys64\mingw64\bin"
        Write-Host "-----------"
        Get-ChildItem -Path "C:\Program Files\Git\mingw64\bin"
        
